# Generated by Django 2.0.6 on 2018-07-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('namel', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashier.Product')),
                ('namey', models.CharField(max_length=250)),
                ('nameh', models.CharField(max_length=250)),
            ],
            bases=('cashier.product',),
        ),
    ]
