# Generated by Django 2.0.6 on 2018-07-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('selling_price', models.CharField(max_length=250)),
                ('available_quantity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_price', models.CharField(max_length=250)),
                ('quantity_purchased', models.CharField(max_length=250)),
                ('date_of_purchase', models.CharField(max_length=250)),
                ('product_in_purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.CharField(max_length=250)),
                ('date_of_sale', models.CharField(max_length=250)),
                ('total_amount', models.CharField(max_length=250)),
                ('product_in_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Products')),
            ],
        ),
        migrations.RemoveField(
            model_name='atom',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Atom',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
