# Generated by Django 2.0.6 on 2018-07-04 15:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cashier', '0002_auto_20180704_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
