# Generated by Django 2.0.6 on 2018-07-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20180704_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('selling_price', models.CharField(max_length=250)),
                ('available_quantity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_price', models.CharField(max_length=250)),
                ('quantity_purchased', models.CharField(max_length=250)),
                ('date_of_purchase', models.CharField(max_length=250)),
                ('product_in_purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Product_model')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.CharField(max_length=250)),
                ('date_of_sale', models.CharField(max_length=250)),
                ('total_amount', models.CharField(max_length=250)),
                ('product_in_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Product_model')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_in_purchases',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_in_sales',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
