# Generated by Django 2.0.6 on 2018-07-04 15:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cashier', '0004_auto_20180704_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_model',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='Purchase_model',
            new_name='Purchases',
        ),
        migrations.RenameModel(
            old_name='Sale_model',
            new_name='Sales',
        ),
    ]
