# Generated by Django 2.0.6 on 2018-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20180704_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_sale',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
