# Generated by Django 2.0.6 on 2018-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20180705_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='Cost_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity_purchased',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
