# Generated by Django 2.0.6 on 2018-07-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_auto_20180706_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
