# Generated by Django 2.0.6 on 2018-07-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=45)),
                ('Contact', models.CharField(max_length=14)),
                ('Country', models.CharField(max_length=25)),
                ('Salary', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.Employee')),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
            bases=('manager.employee',),
        ),
    ]
